name: graphppi
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - torch>=2.0.0
      - torch_geometric>=2.5.0
      - pandas>=2.0.0
      - numpy>=1.24.0
      - scikit-learn>=1.3.0
      - networkx>=3.0
      - node2vec>=0.4.0
      - matplotlib>=3.7.0
      - jupyter
      - pytest
